### ISSUE TITLE
PWA - "Add to home screen" Modal UI

### ISSUE THREAD

**Issue by HamedNN76** [treejer/mobile#41]
We need a modal to inform our users about the PWA for the web,
In this case, users can use the web application as a mobile application to have a better experience and access. 

Tasks:
- [x] UI and implementation: "AddToHomeScreenPWA" component
- [x] Detect user's platform (Android or iOS) for differences on the UI and logic part
  - [x] iOS: Show PWA Modal
  - [x] Android:
    - [ ] If user have the application: Open Application
    - [x] else, suggest user to install application, Download App on Google Play button
- [x] [PWA expo configurations](https://docs.expo.dev/guides/progressive-web-apps/) 
**As a sample you can checkout the native parts for (background-color, splash, favicon, ...)**
- [x] Show PWA Modal when user is on browser

Please consider the other issues that maybe needed to implement for the PWA feature purpose.

**Comment by armin-bkh** [comment]
I really like to collaborate on this project.
My estimation for this task is three days.

**Comment by HamedNN76** [comment]
This is a very great help @armin-bkh 
Can you please start it ASAP?

If yes, please fork this repository, then create a branch called "pwa-setup" and start to do your commits.
Please make sure to make incremental commits.

**Comment by armin-bkh** [comment]
Yes of course I will start ASAP and will keep you posted. @HamedNN76
